# Generated by Django 5.1.6 on 2025-03-14 02:37

import base.models.accounts_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=base.models.accounts_models.create_id, max_length=22, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='無名なユーザー', max_length=20, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('introduction', models.TextField(blank=True, default='')),
                ('age', models.IntegerField(default=0)),
                ('occupation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRecordModel',
            fields=[
                ('id', models.CharField(default=base.models.accounts_models.create_id, max_length=22, primary_key=True, serialize=False)),
                ('work_time', models.IntegerField(default=0)),
                ('rest_time', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
