# Generated by Django 5.1.6 on 2025-03-09 08:38

import base.models.record_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudyRecordModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=base.models.record_models.create_id,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("work_time", models.IntegerField(default=25)),
                ("rest_time", models.IntegerField(default=5)),
                ("total", models.IntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
